<?php
/**
 * EpochsApi
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace melmccann\cardanoexplorer\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use melmccann\cardanoexplorer\ApiException;
use melmccann\cardanoexplorer\Configuration;
use melmccann\cardanoexplorer\HeaderSelector;
use melmccann\cardanoexplorer\ObjectSerializer;

/**
 * EpochsApi Class Doc Comment
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EpochsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation epochPages
     *
     * get epoch
     *
     * @param  int $epoch epoch (required)
     * @param  float $page page (required)
     *
     * @throws \melmccann\cardanoexplorer\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \melmccann\cardanoexplorer\Model\InlineResponse2001
     */
    public function epochPages($epoch, $page)
    {
        list($response) = $this->epochPagesWithHttpInfo($epoch, $page);
        return $response;
    }

    /**
     * Operation epochPagesWithHttpInfo
     *
     * get epoch
     *
     * @param  int $epoch (required)
     * @param  float $page (required)
     *
     * @throws \melmccann\cardanoexplorer\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \melmccann\cardanoexplorer\Model\InlineResponse2001, HTTP status code, HTTP response headers (array of strings)
     */
    public function epochPagesWithHttpInfo($epoch, $page)
    {
        $request = $this->epochPagesRequest($epoch, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\melmccann\cardanoexplorer\Model\InlineResponse2001' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\melmccann\cardanoexplorer\Model\InlineResponse2001', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\melmccann\cardanoexplorer\Model\InlineResponse2001';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\melmccann\cardanoexplorer\Model\InlineResponse2001',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation epochPagesAsync
     *
     * get epoch
     *
     * @param  int $epoch (required)
     * @param  float $page (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function epochPagesAsync($epoch, $page)
    {
        return $this->epochPagesAsyncWithHttpInfo($epoch, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation epochPagesAsyncWithHttpInfo
     *
     * get epoch
     *
     * @param  int $epoch (required)
     * @param  float $page (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function epochPagesAsyncWithHttpInfo($epoch, $page)
    {
        $returnType = '\melmccann\cardanoexplorer\Model\InlineResponse2001';
        $request = $this->epochPagesRequest($epoch, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'epochPages'
     *
     * @param  int $epoch (required)
     * @param  float $page (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function epochPagesRequest($epoch, $page)
    {
        // verify the required parameter 'epoch' is set
        if ($epoch === null || (is_array($epoch) && count($epoch) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $epoch when calling epochPages'
            );
        }
        if ($epoch < 0) {
            throw new \InvalidArgumentException('invalid value for "$epoch" when calling EpochsApi.epochPages, must be bigger than or equal to 0.');
        }

        // verify the required parameter 'page' is set
        if ($page === null || (is_array($page) && count($page) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page when calling epochPages'
            );
        }
        if ($page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling EpochsApi.epochPages, must be bigger than or equal to 1.');
        }


        $resourcePath = '/api/epochs/{epoch}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, '', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }


        // path params
        if ($epoch !== null) {
            $resourcePath = str_replace(
                '{' . 'epoch' . '}',
                ObjectSerializer::toPathValue($epoch),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation epochSlots
     *
     * get slot
     *
     * @param  int $epoch epoch (required)
     * @param  int $slot slot (required)
     *
     * @throws \melmccann\cardanoexplorer\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \melmccann\cardanoexplorer\Model\InlineResponse2009
     */
    public function epochSlots($epoch, $slot)
    {
        list($response) = $this->epochSlotsWithHttpInfo($epoch, $slot);
        return $response;
    }

    /**
     * Operation epochSlotsWithHttpInfo
     *
     * get slot
     *
     * @param  int $epoch (required)
     * @param  int $slot (required)
     *
     * @throws \melmccann\cardanoexplorer\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \melmccann\cardanoexplorer\Model\InlineResponse2009, HTTP status code, HTTP response headers (array of strings)
     */
    public function epochSlotsWithHttpInfo($epoch, $slot)
    {
        $request = $this->epochSlotsRequest($epoch, $slot);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\melmccann\cardanoexplorer\Model\InlineResponse2009' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\melmccann\cardanoexplorer\Model\InlineResponse2009', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\melmccann\cardanoexplorer\Model\InlineResponse2009';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\melmccann\cardanoexplorer\Model\InlineResponse2009',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation epochSlotsAsync
     *
     * get slot
     *
     * @param  int $epoch (required)
     * @param  int $slot (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function epochSlotsAsync($epoch, $slot)
    {
        return $this->epochSlotsAsyncWithHttpInfo($epoch, $slot)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation epochSlotsAsyncWithHttpInfo
     *
     * get slot
     *
     * @param  int $epoch (required)
     * @param  int $slot (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function epochSlotsAsyncWithHttpInfo($epoch, $slot)
    {
        $returnType = '\melmccann\cardanoexplorer\Model\InlineResponse2009';
        $request = $this->epochSlotsRequest($epoch, $slot);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'epochSlots'
     *
     * @param  int $epoch (required)
     * @param  int $slot (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function epochSlotsRequest($epoch, $slot)
    {
        // verify the required parameter 'epoch' is set
        if ($epoch === null || (is_array($epoch) && count($epoch) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $epoch when calling epochSlots'
            );
        }
        if ($epoch < 0) {
            throw new \InvalidArgumentException('invalid value for "$epoch" when calling EpochsApi.epochSlots, must be bigger than or equal to 0.');
        }

        // verify the required parameter 'slot' is set
        if ($slot === null || (is_array($slot) && count($slot) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $slot when calling epochSlots'
            );
        }
        if ($slot > 65535) {
            throw new \InvalidArgumentException('invalid value for "$slot" when calling EpochsApi.epochSlots, must be smaller than or equal to 65535.');
        }
        if ($slot < 0) {
            throw new \InvalidArgumentException('invalid value for "$slot" when calling EpochsApi.epochSlots, must be bigger than or equal to 0.');
        }


        $resourcePath = '/api/epochs/{epoch}/{slot}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($epoch !== null) {
            $resourcePath = str_replace(
                '{' . 'epoch' . '}',
                ObjectSerializer::toPathValue($epoch),
                $resourcePath
            );
        }
        // path params
        if ($slot !== null) {
            $resourcePath = str_replace(
                '{' . 'slot' . '}',
                ObjectSerializer::toPathValue($slot),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
