<?php
/**
 * CTxAddressBrief
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace melmccann\cardanoexplorer\Model;

use \ArrayAccess;
use \melmccann\cardanoexplorer\ObjectSerializer;

/**
 * CTxAddressBrief Class Doc Comment
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CTxAddressBrief implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CTxAddressBrief';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cta_address' => 'string',
        'cta_amount' => '\melmccann\cardanoexplorer\Model\InlineResponse200RightCoin',
        'cta_tx_hash' => 'object',
        'cta_tx_index' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'cta_address' => 'base58',
        'cta_amount' => null,
        'cta_tx_hash' => null,
        'cta_tx_index' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cta_address' => 'ctaAddress',
        'cta_amount' => 'ctaAmount',
        'cta_tx_hash' => 'ctaTxHash',
        'cta_tx_index' => 'ctaTxIndex'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cta_address' => 'setCtaAddress',
        'cta_amount' => 'setCtaAmount',
        'cta_tx_hash' => 'setCtaTxHash',
        'cta_tx_index' => 'setCtaTxIndex'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cta_address' => 'getCtaAddress',
        'cta_amount' => 'getCtaAmount',
        'cta_tx_hash' => 'getCtaTxHash',
        'cta_tx_index' => 'getCtaTxIndex'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cta_address'] = isset($data['cta_address']) ? $data['cta_address'] : null;
        $this->container['cta_amount'] = isset($data['cta_amount']) ? $data['cta_amount'] : null;
        $this->container['cta_tx_hash'] = isset($data['cta_tx_hash']) ? $data['cta_tx_hash'] : null;
        $this->container['cta_tx_index'] = isset($data['cta_tx_index']) ? $data['cta_tx_index'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cta_address'] === null) {
            $invalidProperties[] = "'cta_address' can't be null";
        }
        if ($this->container['cta_amount'] === null) {
            $invalidProperties[] = "'cta_amount' can't be null";
        }
        if ($this->container['cta_tx_hash'] === null) {
            $invalidProperties[] = "'cta_tx_hash' can't be null";
        }
        if ($this->container['cta_tx_index'] === null) {
            $invalidProperties[] = "'cta_tx_index' can't be null";
        }
        if (($this->container['cta_tx_index'] < 0)) {
            $invalidProperties[] = "invalid value for 'cta_tx_index', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cta_address
     *
     * @return string
     */
    public function getCtaAddress()
    {
        return $this->container['cta_address'];
    }

    /**
     * Sets cta_address
     *
     * @param string $cta_address cta_address
     *
     * @return $this
     */
    public function setCtaAddress($cta_address)
    {
        $this->container['cta_address'] = $cta_address;

        return $this;
    }

    /**
     * Gets cta_amount
     *
     * @return \melmccann\cardanoexplorer\Model\InlineResponse200RightCoin
     */
    public function getCtaAmount()
    {
        return $this->container['cta_amount'];
    }

    /**
     * Sets cta_amount
     *
     * @param \melmccann\cardanoexplorer\Model\InlineResponse200RightCoin $cta_amount cta_amount
     *
     * @return $this
     */
    public function setCtaAmount($cta_amount)
    {
        $this->container['cta_amount'] = $cta_amount;

        return $this;
    }

    /**
     * Gets cta_tx_hash
     *
     * @return object
     */
    public function getCtaTxHash()
    {
        return $this->container['cta_tx_hash'];
    }

    /**
     * Sets cta_tx_hash
     *
     * @param object $cta_tx_hash cta_tx_hash
     *
     * @return $this
     */
    public function setCtaTxHash($cta_tx_hash)
    {
        $this->container['cta_tx_hash'] = $cta_tx_hash;

        return $this;
    }

    /**
     * Gets cta_tx_index
     *
     * @return int
     */
    public function getCtaTxIndex()
    {
        return $this->container['cta_tx_index'];
    }

    /**
     * Sets cta_tx_index
     *
     * @param int $cta_tx_index cta_tx_index
     *
     * @return $this
     */
    public function setCtaTxIndex($cta_tx_index)
    {

        if (($cta_tx_index < 0)) {
            throw new \InvalidArgumentException('invalid value for $cta_tx_index when calling CTxAddressBrief., must be bigger than or equal to 0.');
        }

        $this->container['cta_tx_index'] = $cta_tx_index;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


