<?php
/**
 * InlineResponse2003Right
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InlineResponse2003Right Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InlineResponse2003Right implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_3_Right';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cbs_entry' => '\OpenAPI\Client\Model\InlineResponse2003RightCbsEntry',
        'cbs_prev_hash' => 'string',
        'cbs_next_hash' => 'string',
        'cbs_merkle_root' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'cbs_entry' => null,
        'cbs_prev_hash' => 'base16',
        'cbs_next_hash' => 'base16',
        'cbs_merkle_root' => 'base16'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cbs_entry' => 'cbsEntry',
        'cbs_prev_hash' => 'cbsPrevHash',
        'cbs_next_hash' => 'cbsNextHash',
        'cbs_merkle_root' => 'cbsMerkleRoot'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cbs_entry' => 'setCbsEntry',
        'cbs_prev_hash' => 'setCbsPrevHash',
        'cbs_next_hash' => 'setCbsNextHash',
        'cbs_merkle_root' => 'setCbsMerkleRoot'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cbs_entry' => 'getCbsEntry',
        'cbs_prev_hash' => 'getCbsPrevHash',
        'cbs_next_hash' => 'getCbsNextHash',
        'cbs_merkle_root' => 'getCbsMerkleRoot'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cbs_entry'] = isset($data['cbs_entry']) ? $data['cbs_entry'] : null;
        $this->container['cbs_prev_hash'] = isset($data['cbs_prev_hash']) ? $data['cbs_prev_hash'] : null;
        $this->container['cbs_next_hash'] = isset($data['cbs_next_hash']) ? $data['cbs_next_hash'] : null;
        $this->container['cbs_merkle_root'] = isset($data['cbs_merkle_root']) ? $data['cbs_merkle_root'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cbs_entry'] === null) {
            $invalidProperties[] = "'cbs_entry' can't be null";
        }
        if ($this->container['cbs_prev_hash'] === null) {
            $invalidProperties[] = "'cbs_prev_hash' can't be null";
        }
        if ((mb_strlen($this->container['cbs_prev_hash']) > 64)) {
            $invalidProperties[] = "invalid value for 'cbs_prev_hash', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['cbs_prev_hash']) < 64)) {
            $invalidProperties[] = "invalid value for 'cbs_prev_hash', the character length must be bigger than or equal to 64.";
        }

        if (!preg_match("/^[0-9a-f]{64}$/", $this->container['cbs_prev_hash'])) {
            $invalidProperties[] = "invalid value for 'cbs_prev_hash', must be conform to the pattern /^[0-9a-f]{64}$/.";
        }

        if (!is_null($this->container['cbs_next_hash']) && (mb_strlen($this->container['cbs_next_hash']) > 64)) {
            $invalidProperties[] = "invalid value for 'cbs_next_hash', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['cbs_next_hash']) && (mb_strlen($this->container['cbs_next_hash']) < 64)) {
            $invalidProperties[] = "invalid value for 'cbs_next_hash', the character length must be bigger than or equal to 64.";
        }

        if (!is_null($this->container['cbs_next_hash']) && !preg_match("/^[0-9a-f]{64}$/", $this->container['cbs_next_hash'])) {
            $invalidProperties[] = "invalid value for 'cbs_next_hash', must be conform to the pattern /^[0-9a-f]{64}$/.";
        }

        if ($this->container['cbs_merkle_root'] === null) {
            $invalidProperties[] = "'cbs_merkle_root' can't be null";
        }
        if ((mb_strlen($this->container['cbs_merkle_root']) > 64)) {
            $invalidProperties[] = "invalid value for 'cbs_merkle_root', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['cbs_merkle_root']) < 64)) {
            $invalidProperties[] = "invalid value for 'cbs_merkle_root', the character length must be bigger than or equal to 64.";
        }

        if (!preg_match("/^[0-9a-f]{64}$/", $this->container['cbs_merkle_root'])) {
            $invalidProperties[] = "invalid value for 'cbs_merkle_root', must be conform to the pattern /^[0-9a-f]{64}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cbs_entry
     *
     * @return \OpenAPI\Client\Model\InlineResponse2003RightCbsEntry
     */
    public function getCbsEntry()
    {
        return $this->container['cbs_entry'];
    }

    /**
     * Sets cbs_entry
     *
     * @param \OpenAPI\Client\Model\InlineResponse2003RightCbsEntry $cbs_entry cbs_entry
     *
     * @return $this
     */
    public function setCbsEntry($cbs_entry)
    {
        $this->container['cbs_entry'] = $cbs_entry;

        return $this;
    }

    /**
     * Gets cbs_prev_hash
     *
     * @return string
     */
    public function getCbsPrevHash()
    {
        return $this->container['cbs_prev_hash'];
    }

    /**
     * Sets cbs_prev_hash
     *
     * @param string $cbs_prev_hash cbs_prev_hash
     *
     * @return $this
     */
    public function setCbsPrevHash($cbs_prev_hash)
    {
        if ((mb_strlen($cbs_prev_hash) > 64)) {
            throw new \InvalidArgumentException('invalid length for $cbs_prev_hash when calling InlineResponse2003Right., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($cbs_prev_hash) < 64)) {
            throw new \InvalidArgumentException('invalid length for $cbs_prev_hash when calling InlineResponse2003Right., must be bigger than or equal to 64.');
        }
        if ((!preg_match("/^[0-9a-f]{64}$/", $cbs_prev_hash))) {
            throw new \InvalidArgumentException("invalid value for $cbs_prev_hash when calling InlineResponse2003Right., must conform to the pattern /^[0-9a-f]{64}$/.");
        }

        $this->container['cbs_prev_hash'] = $cbs_prev_hash;

        return $this;
    }

    /**
     * Gets cbs_next_hash
     *
     * @return string|null
     */
    public function getCbsNextHash()
    {
        return $this->container['cbs_next_hash'];
    }

    /**
     * Sets cbs_next_hash
     *
     * @param string|null $cbs_next_hash cbs_next_hash
     *
     * @return $this
     */
    public function setCbsNextHash($cbs_next_hash)
    {
        if (!is_null($cbs_next_hash) && (mb_strlen($cbs_next_hash) > 64)) {
            throw new \InvalidArgumentException('invalid length for $cbs_next_hash when calling InlineResponse2003Right., must be smaller than or equal to 64.');
        }
        if (!is_null($cbs_next_hash) && (mb_strlen($cbs_next_hash) < 64)) {
            throw new \InvalidArgumentException('invalid length for $cbs_next_hash when calling InlineResponse2003Right., must be bigger than or equal to 64.');
        }
        if (!is_null($cbs_next_hash) && (!preg_match("/^[0-9a-f]{64}$/", $cbs_next_hash))) {
            throw new \InvalidArgumentException("invalid value for $cbs_next_hash when calling InlineResponse2003Right., must conform to the pattern /^[0-9a-f]{64}$/.");
        }

        $this->container['cbs_next_hash'] = $cbs_next_hash;

        return $this;
    }

    /**
     * Gets cbs_merkle_root
     *
     * @return string
     */
    public function getCbsMerkleRoot()
    {
        return $this->container['cbs_merkle_root'];
    }

    /**
     * Sets cbs_merkle_root
     *
     * @param string $cbs_merkle_root cbs_merkle_root
     *
     * @return $this
     */
    public function setCbsMerkleRoot($cbs_merkle_root)
    {
        if ((mb_strlen($cbs_merkle_root) > 64)) {
            throw new \InvalidArgumentException('invalid length for $cbs_merkle_root when calling InlineResponse2003Right., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($cbs_merkle_root) < 64)) {
            throw new \InvalidArgumentException('invalid length for $cbs_merkle_root when calling InlineResponse2003Right., must be bigger than or equal to 64.');
        }
        if ((!preg_match("/^[0-9a-f]{64}$/", $cbs_merkle_root))) {
            throw new \InvalidArgumentException("invalid value for $cbs_merkle_root when calling InlineResponse2003Right., must conform to the pattern /^[0-9a-f]{64}$/.");
        }

        $this->container['cbs_merkle_root'] = $cbs_merkle_root;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


