<?php
/**
 * CBlockEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccann\cardanoexplorer;

use PHPUnit\Framework\TestCase;

/**
 * CBlockEntryTest Class Doc Comment
 *
 * @category    Class
 * @description CBlockEntry
 * @package     melmccann\cardanoexplorer
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CBlockEntryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CBlockEntry"
     */
    public function testCBlockEntry()
    {
    }

    /**
     * Test attribute "cbe_epoch"
     */
    public function testPropertyCbeEpoch()
    {
    }

    /**
     * Test attribute "cbe_slot"
     */
    public function testPropertyCbeSlot()
    {
    }

    /**
     * Test attribute "cbe_blk_height"
     */
    public function testPropertyCbeBlkHeight()
    {
    }

    /**
     * Test attribute "cbe_blk_hash"
     */
    public function testPropertyCbeBlkHash()
    {
    }

    /**
     * Test attribute "cbe_time_issued"
     */
    public function testPropertyCbeTimeIssued()
    {
    }

    /**
     * Test attribute "cbe_tx_num"
     */
    public function testPropertyCbeTxNum()
    {
    }

    /**
     * Test attribute "cbe_total_sent"
     */
    public function testPropertyCbeTotalSent()
    {
    }

    /**
     * Test attribute "cbe_size"
     */
    public function testPropertyCbeSize()
    {
    }

    /**
     * Test attribute "cbe_block_lead"
     */
    public function testPropertyCbeBlockLead()
    {
    }

    /**
     * Test attribute "cbe_fees"
     */
    public function testPropertyCbeFees()
    {
    }
}
