<?php
/**
 * CGenesisAddressInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccann\cardanoexplorer;

use PHPUnit\Framework\TestCase;

/**
 * CGenesisAddressInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CGenesisAddressInfo
 * @package     melmccann\cardanoexplorer
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CGenesisAddressInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CGenesisAddressInfo"
     */
    public function testCGenesisAddressInfo()
    {
    }

    /**
     * Test attribute "cgai_cardano_address"
     */
    public function testPropertyCgaiCardanoAddress()
    {
    }

    /**
     * Test attribute "cgai_genesis_amount"
     */
    public function testPropertyCgaiGenesisAmount()
    {
    }

    /**
     * Test attribute "cgai_is_redeemed"
     */
    public function testPropertyCgaiIsRedeemed()
    {
    }
}
