<?php
/**
 * InlineResponse2006RightTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2006RightTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2006Right
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2006RightTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2006Right"
     */
    public function testInlineResponse2006Right()
    {
    }

    /**
     * Test attribute "cts_id"
     */
    public function testPropertyCtsId()
    {
    }

    /**
     * Test attribute "cts_tx_time_issued"
     */
    public function testPropertyCtsTxTimeIssued()
    {
    }

    /**
     * Test attribute "cts_block_time_issued"
     */
    public function testPropertyCtsBlockTimeIssued()
    {
    }

    /**
     * Test attribute "cts_block_height"
     */
    public function testPropertyCtsBlockHeight()
    {
    }

    /**
     * Test attribute "cts_block_epoch"
     */
    public function testPropertyCtsBlockEpoch()
    {
    }

    /**
     * Test attribute "cts_block_slot"
     */
    public function testPropertyCtsBlockSlot()
    {
    }

    /**
     * Test attribute "cts_block_hash"
     */
    public function testPropertyCtsBlockHash()
    {
    }

    /**
     * Test attribute "cts_relayed_by"
     */
    public function testPropertyCtsRelayedBy()
    {
    }

    /**
     * Test attribute "cts_total_input"
     */
    public function testPropertyCtsTotalInput()
    {
    }

    /**
     * Test attribute "cts_total_output"
     */
    public function testPropertyCtsTotalOutput()
    {
    }

    /**
     * Test attribute "cts_fees"
     */
    public function testPropertyCtsFees()
    {
    }

    /**
     * Test attribute "cts_inputs"
     */
    public function testPropertyCtsInputs()
    {
    }

    /**
     * Test attribute "cts_outputs"
     */
    public function testPropertyCtsOutputs()
    {
    }
}
