<?php
/**
 * InlineResponse2008RightTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2008RightTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2008Right
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2008RightTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2008Right"
     */
    public function testInlineResponse2008Right()
    {
    }

    /**
     * Test attribute "ca_address"
     */
    public function testPropertyCaAddress()
    {
    }

    /**
     * Test attribute "ca_type"
     */
    public function testPropertyCaType()
    {
    }

    /**
     * Test attribute "ca_chain_tip"
     */
    public function testPropertyCaChainTip()
    {
    }

    /**
     * Test attribute "ca_tx_num"
     */
    public function testPropertyCaTxNum()
    {
    }

    /**
     * Test attribute "ca_balance"
     */
    public function testPropertyCaBalance()
    {
    }

    /**
     * Test attribute "ca_total_input"
     */
    public function testPropertyCaTotalInput()
    {
    }

    /**
     * Test attribute "ca_total_output"
     */
    public function testPropertyCaTotalOutput()
    {
    }

    /**
     * Test attribute "ca_total_fee"
     */
    public function testPropertyCaTotalFee()
    {
    }

    /**
     * Test attribute "ca_tx_list"
     */
    public function testPropertyCaTxList()
    {
    }
}
