<?php
/**
 * InlineResponse2004RightTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2004RightTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2004Right
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2004RightTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2004Right"
     */
    public function testInlineResponse2004Right()
    {
    }

    /**
     * Test attribute "ctb_id"
     */
    public function testPropertyCtbId()
    {
    }

    /**
     * Test attribute "ctb_time_issued"
     */
    public function testPropertyCtbTimeIssued()
    {
    }

    /**
     * Test attribute "ctb_inputs"
     */
    public function testPropertyCtbInputs()
    {
    }

    /**
     * Test attribute "ctb_outputs"
     */
    public function testPropertyCtbOutputs()
    {
    }

    /**
     * Test attribute "ctb_input_sum"
     */
    public function testPropertyCtbInputSum()
    {
    }

    /**
     * Test attribute "ctb_output_sum"
     */
    public function testPropertyCtbOutputSum()
    {
    }

    /**
     * Test attribute "ctb_fees"
     */
    public function testPropertyCtbFees()
    {
    }
}
