<?php
/**
 * InlineResponse2005RightTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanoexplorer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cardano-explorer-api
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccann\cardanoexplorer;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2005RightTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2005Right
 * @package     melmccann\cardanoexplorer
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2005RightTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2005Right"
     */
    public function testInlineResponse2005Right()
    {
    }

    /**
     * Test attribute "cte_id"
     */
    public function testPropertyCteId()
    {
    }

    /**
     * Test attribute "cte_time_issued"
     */
    public function testPropertyCteTimeIssued()
    {
    }

    /**
     * Test attribute "cte_amount"
     */
    public function testPropertyCteAmount()
    {
    }
}
